### PR TITLE
added params for aliases, builtIns, builtInTypes

### PR DESCRIPTION
**Pull request by irrationalistic**
This will go along with some changes on the vim side as well!

### CODE REVIEW

**Comment by gillesruppert** [comment]
Thanks @irrationalistic! This looks pretty neat. Would you mind adding a couple of lines to the README on how to use this? (i.e. use `=` as a separator or not, etc.)

**Comment by irrationalistic** [comment]
Sure! Will update when I get the chance :)

**Comment by irrationalistic** [comment]
Ok, added the arguments to the readme!

**Comment by gillesruppert** [comment]
Thanks a lot @irrationalistic

**Pull request merged**
